<html>
    <head>

    <?php echo
    $this->headLink()->prependStylesheet('/css/gallantnyc.css')
        ->prependStylesheet('/bootstrap/css/bootstrap.min.css')
    ?>

    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
        ->prependFile($this->basePath() . '/bootstrap/bootstrap.min.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ?>

        <script type="text/javascript">
            $('.carousel').carousel({
            interval: 2000
        })
        </script>
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>

</html>