<!DOCTYPE html>
<html>
<head>
    <title>GoddessAmor.com</title>
    <link href="/amor/goddessamor.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/amor/goddessamor-media-queries.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
</head>
<body>
<div id="pagewrap">
    <header id="header">
        <div class="goHeader">
            <img src="/amor/amor_logo.png" />
        </div>
    </header>
    <div id="content">
        <div class="screen"><img src="/amor/amor_screen.png" border="0" /></div>
        <div id="infoBoard">&nbsp;</div>
    </div>
    <div id="sidebar">
        &nbsp;
    </div>
</div>
</body>

</html