<div>

    Photo page
    <!-- class of slide for animation -->

    <!--
    <div class="carousel-inner">
        <div class="item active">
            <img src="/images/photography/photo1.jpg" width="1000px" height="700px;"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
        <div class="item">
            <img src="/images/photography/photo2.jpg" width="1000px" height="700px"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
        <div class="item">
            <img src="/images/photography/photo3.jpg" width="1000px" height="700px"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
    </div>
    -->
</div>

