    <div id="myCarousel" class="carousel slide">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item"><img src="/images/clients/client_gm.jpg" /></div>
            <div class="item"><img src="/images/clients/client_noah.jpg" /></div>
            <div class="item"><img src="/images/clients/client_canopy.jpg" /></div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
