<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
    <div class="carousel-inner">
        <div class="item active"><!-- class of active since it's the first item -->
            <img src="/images/photography/photo1.jpg" width="1000px" height="700px;"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
        <div class="item">
            <img src="/images/photography/photo2.jpg" width="1000px" height="700px"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
        <div class="item">
            <img src="/images/photography/photo3.jpg" width="1000px" height="700px"/>
            <div class="carousel-caption">
                <p>Caption text here</p>
            </div>
        </div>
    </div><!-- /.carousel-inner -->
    <!--  Next and Previous controls below
href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

