<!DOCTYPE html>
<html>
<head>
    <title>GoddessNYC.com</title>
    <link href="/one/one.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/one/one-media-queries.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
</head>
<body>
<img alt="full screen background image" src="/one/gg_sunset.png" id="full-screen-background-image" />
<div id="pagewrap">
    <header id="header">
        <div class="goHeader">
            <img src="/one/one_logo.png" />
        </div>
        <div class="goLine"></div>
    </header>
    <div class="textHeader">
        <h1>RELIABLE ENGINEERING & DESIGN</h1>
        <h3>KEEPING THE DIGITAL WORLD INNOVATIVE AND VISUALLY REMARKABLE</h3>
    </div>
    <div class="goBoxes">

        <div class="descBox">
            <div class="gSubHeader"><img src="/one/flange.png"/>Digital Artistry</div>
            <div class="line_540"></div>
        <p>The task of building robust, high-capacity enterprise-level Web applications and information systems is the everyday challenge for stalwart multi-faceted engineer.</p>
        <p>    When it comes to design and corporate identity, the need for an engineer who understands the principles and intricities of fluid UI design becomes essential.</p>

        <p>These are but a few principles within GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</p>
            <div id="viewButton"><img src="/one/button_view.png" /></div>
        </div>
        <div class="aboutBox">
            <div class="gSubHeader"><img src="/one/flange.png"/>The Architect</div>
            <div class="line_240"></div>
            <p>Greg A. Gallant is a professional technologist and software engineer and web designer with over 14 years of experience working in New York City.</p>

            <p>Specializations and experience include the building of several small technology companies using a multitude of programming languages including Java Spring MVC 3, PHP Zend 2 Framework and CodeIgniter, Python, Javascript, and JQuery. This includes database programming using MySQL, Oracle, and PostGreSQL.</p>
        </div>
    </div>
</div>
</body>

</html>