<div class="portLeftWidth">
<div style="margin-left:5px; margin-top:0px;">
    <div class="portClientName"><?php echo $client->getName(); ?></div>
    <div class="portDetails"><?php echo $client->getDetails(); ?></div>
    <div style="margin-top:10px;font-size:11pt; text-align:right"><a name="learnMore" class="button orange" id="learnMore<?php echo $client->getId(); ?>" href="#">Learn More</a></div>
</div>
</div>