<div id="textHeader">
    <h1>RELIABLE ENGINEERING & DESIGN</h1>
    <h3>KEEPING THE DIGITAL WORLD INNOVATIVE AND VISUALLY REMARKABLE</h3>
</div>
<div id="goBoxes">
    <div class="descBox">
        <div class="gSubHeader"><img src="/images/one/flange.png"/>Digital Artistry</div>
        <div class="line_540"></div>
        <p>The task of building robust, high-capacity enterprise-level Web applications and information systems is the everyday challenge for stalwart multi-faceted engineer.</p>
        <p>    When it comes to design and corporate identity, the need for an engineer who understands the principles and intricities of fluid UI design becomes essential.</p>

        <p>These are but a few principles within GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</p>
        <div id="viewButton"><a href="/portfolio/1"><img border="0" src="/images/one/button_view.png" /></a></div>
    </div>
    <div class="aboutBox">
        <div class="gSubHeader"><img src="/images/one/flange.png"/>The Architect</div>
        <div class="line_240"></div>
        <p>            <strong>Greg A. Gallant</strong> is a professional
            technologist and software engineer and web designer
            with over 14 years of experience working in New York City.
            <br/>
            <br/>
            Specializations and experience include the building of several small technology companies using a multitude of programming languages including <a target="springsource" href="http://springsource.org">Java Spring MVC 3</a>, <a target="php" href="http://www.php.net">PHP</a> <a href="http://framework.zend.com">Zend 2 Framework</a> and <a href="http://ellislab.com/codeigniter">CodeIgniter</a>, <a href="http://www.python.org">Python</a>, Javascript, and <a href="http://jquery.com">JQuery</a>. This includes database programming using <a href="http://www.mysql.com">MySQL</a>, <a href="http://www.oracle.com">Oracle</a>, and <a href="http://www.postgresql.org">PostGreSQL</a>.</p>
        <div id="contactButton"><a href="/contact"><img border="0" src="/images/one/button_contact.png" /></a></div>
    </div>
</div>

