<div class="leftFrontPanel">

    <h2> Reliable Engineering, Design, and Growth </h2>
    <div>
        <p class="frontText">
            The task of building robust, high-capacity enterprise-level Web applications and information systems is
            the everyday challenge for stalwart multi-faceted engineer.  As a multi-faceted engineer, I have specialized
            in taking small start-ups with large ideas and melding them into successful and flourshing enterprises.  When it comes
            to design and corporate identity, the need for an engineer who understands the principles and intricities of
            fluid UI design becomes essential.
        </p>
        <p class="frontText">
            That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant.  Brining ideas
            to a technological life is the everyday challenge that keeps the digital world moving and what essentially
            keeps myself up to par as a professional company builder.
        </p>
        <p class="frontText">
            Have an idea, or a master plan?  Contact me at <a href="mailto:greggallant2005@gmail.com">greggallant2005@gmail.com</a> or <a href="mailto:greg@gallantone.com">greg@gallantone.com</a> and let's create the digital subverse.
        </p>
    </div>
</div>