<script src="external/jquery-1.6.2.js"></script>
<script type="text/javascript" src="js/html2canvas.js"></script>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/goport.js')
<script type="text/javascript">
    $(document).ready(function() {
        $('body').html2canvas();
        var queue = html2canvas.Parse();
        var canvas = html2canvas.Renderer(queue,{elements:{length:1}});
        var img = canvas.toDataURL()
        window.open(img);
    });
</script>
</head>

    <body>
    <h1>Testing</h1>
    <img src='http://localhost:8080/test/images/1.jpg'>