
<!-- This is a menu partial -->
<div style="font-size:12pt; font-weight:bold; font-family:Arial,sans-serif; color:#cffc93; margin:10px;">GallantOne.com Administration</div>
<?php echo $this->partial("admin/admin/adminmenu.phtml"); ?>


<!-- Content Partial -->
<?php
    if ($thisRoute != '/admin/') {
        echo $this->partial("admin".$thisRoute);
    } else {
        echo "<!--ij10
        85568-KC5N7-GQ5K0-J6UAT-JYOF6-FUXL7 Sergei
        85568-7G9DP-WNYWZ-32P74-1DHAL-5QAT7 Greg
        85568-OYQ5W-L29EE-DWW7Z-TDGDE-TEP65 Me
        Licensed under: Journalism Online, LLC.-->";
    }
?>
