<style type="text/css">

    .link {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 11px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.4em;
        margin-bottom:4px;
        background-color:#090a19;
    }

    .desc {
        margin-left:5px;
        font-family: Helvetica, Arial, sans-serif;
        font-size: 11px;
        font-style: italic;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.42em;
    }

</style>
    <h5>Resources</h5>
<h6>PHP</h6>

<div class="link"><a target="gg" href="http://phpmaster.com/creating-a-php-oauth-server/">phpmaster.com</a></div>
<div class="link"><a target="gg" href="http://websec.io/2013/01/21/Password-Hashing-with-Zend-Crypt.html">zend-crypt</a></div>
<div class="link"><a target="gg" href="http://www.maltblue.com/tutorial/zend-framework-2-event-manager-a-gentle-introduction">ZF2 Event Manager</a></div>
<div class="link"><a target="gg" href="http://phpweekly.info/archive/">phpweekly.info</a></div>
<div class="link"><a target="gg" href="http://blog.ulf-wendel.de/2013/toying-with-peclmysqlnd_memcache-and-mysql-5-6-memcache-innodb/">mysql memcache optimization</a></div>
<div class="link"><a target="gg" href="http://www.maltblue.com/articles-2/zend-framework-2-core-concepts-understanding-dependency-injection">DI Zend Framework</a></div>
<div class="link"><a target="gg" href="http://www.maltblue.com/tutorial/zend-framework-2-servicemanager">ZF2 Service Manager</a></div>
<div class="link"><a target="gg" href="http://www.reddit.com/r/PHP/comments/17a6r4/where_do_you_go_for_your_php_news/">/r/php</a></div>
<div class="link"><a target="gg" href="http://lucadaniel.ro/2013/01/27/concurrent-ajax-requests-and-php/">Concurrent Ajax</a></div>
<div class="link"><a target="gg" href="http://phpmaster.com/dependency-injection-with-pimple/">DI and pimple</a></div>


<h6>CSS</h6>
<div class="link"><a target="gg" href="http://www.modern.ie/report#http%3A%2F%2Fwww.gallantone.com">Modern.ie</a>
    <div class="desc">Browser compatibility tests</div>
</div>

<div class="link"><a target="gg" href="http://www.typetester.org">TypeTester.org</a>
    <div class="desc">View CSS styles for text bodies</div>
</div>

<div class="link"><a target="gg" href="http://www.typechart.com">TypeChart.com</a>
    <div class="desc">The Typography source of magic</div>
</div>

<div class="link"><a target="gg" href="http://www.designwoop.com">DesignWoop.com</a>
    <div class="desc">Css and Jquery idea site</div>
</div>

<h6>jQuery</h6>
<div class="link"><a target="gg" href="http://html2canvas.hertzen.com/">HTML2Canvas</a>
    <div class="desc">A pretty cool textual effect</div>
</div>
<div class="link"><a target="gg" href="http://kiro.me/projects/textualizer.html">Textualizer</a>
    <div class="desc">A pretty cool textual effect</div>
</div>


<h6>Magento</h6>
<div class="link"><a target="gg" href="http://blog.storybloks.com/tag/category/">Magento API via Storybloks.com</a></div>

<h6>Responsive Design</h6>
<div class="link"><a target="gg" href="http://line25.com/tutorials/create-a-responsive-web-design-with-media-queries">Responsive Design - Media Queries</a></div>
<div class="link"><a target="gg" href="http://webdesignerwall.com/tutorials/responsive-design-with-css3-media-queries">HTML 5 /CSS 3 app design</a></div>
<div class="link"><a target="gg" href="http://msdn.microsoft.com/en-us/magazine/hh653584.aspx">MSDN's take on Responsive Design</a></div>

<h6>Other Links</h6>
<div class="link"><a target="gg" href="http://www.vectorstock.com/royalty-free-vectors/">Royalty Free Vectors</a></div>
<div class="link"><a target="gg" href="http://colorschemedesigner.com/">CutyCapt Website Capture</a></div>
<div class="link"><a target="gg" href="http://cutycapt.sourceforge.net/">CutyCapt Website Capture</a></div>
<div class="link"><a target="gg" href="http://iecapt.sourceforge.net/">IECapt Website Capture</a></div>
<div class="link"><a target="gg" href="http://subtlepatterns.com/3px-tile/">Texture Patterns</a></div>
