
<style type="text/css">

    .typeSheet {
        height:100%; font-family:arial,sans-serif; background-color:#ffffff; color:#000000; padding:5px; border:1px solid #333333; padding-bottom:1500px;
    }

    .gClass {
        float:left;
        margin:5px 5px 10px 5px;
        padding:0px 8px 0px 8px;
        font-size:8pt;
        background-color:#9fccf9;
    }

    h1 {
        font-family: Verdana, sans-serif;
        font-size: 44px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: -2px;
        line-height: 1.2em;
    }

    h2 {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 44px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: -2px;
        line-height: 1.2em;

    }

    h3 {
        font-family: “Lucida Sans Unicode”, sans-serif;
        font-size: 44px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: -3px;
        line-height: 1.2em;
    }



    h4 {
        font-family: “Trebuchet MS”, sans-serif;
        font-size: 24px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: -1px;
        line-height: 1.2em;
    }


    h5 {
        font-family: “Lucida Grande”, sans-serif;
        font-size: 22px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: -1px;
        line-height: 1.4em;

    }


    h6 {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 16px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.4em;

    }

    .boldish {
        font-family: “Lucida Grande”, sans-serif;
        font-size: 15px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: -0.6px;
        line-height: 1.5em;

    }

    .standard {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 15px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.45em;
    }

    .fineText {
        font-family: “Lucida Grande”, sans-serif;
        font-size: 10.4px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.5em;
    }

    .pointish {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 11px;
        font-style: italic;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.42em;
    }

    .hpointish {
        font-family: “Lucida Grande”, sans-serif;
        font-size: 10.4px;
        font-style: italic;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.5em;
    }

    .details {
        font-family: Helvetica, Arial, sans-serif;
        font-size: 11px;
        font-style: normal;
        font-weight: bold;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.4em;
    }

    .upper {
        font-family: “Lucida Grande”, sans-serif;
        font-size: 10.4px;
        font-style: normal;
        font-weight: normal;
        text-transform: uppercase;
        letter-spacing: normal;
        line-height: 1.8em;
    }

    .cleanText {
        font-family: “Lucida Sans Unicode”, sans-serif;
        font-size: 12px;
        font-style: normal;
        font-weight: normal;
        text-transform: normal;
        letter-spacing: normal;
        line-height: 1.5em;Close

    }

</style>



<div class="typeSheet">
<strong>GallantOne.com Typography</strong>
    <hr/>


    <div class="gClass">h1</div>
    <h1>This is a header that is big and bold.  Use this to make a solid point.</h1>

    <div class="gClass">h2</div>
    <h2>Another header type for something important, like building your empire.</h2>

    <div class="gClass">h3</div>
    <h3>An individualistic header for individualism, and specific items or properties.</h3>

    <div class="gClass">h4</div>
    <h4>A brief, it's important, but don't let it get carried away.</h4>

    <div class="gClass">h5</div>
    <h5>A brief, it's important, but don't let it get carried away.</h5>

    <div class="gClass">h6</div>
    <h6>A brief, it's important, but don't let it get carried away.</h6>

    <br/>
    <div class="gClass">boldish</div>
    <div class="boldish">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">standard</div>
    <div class="standard">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
<br/>
    <div class="gClass">fineText</div>
    <div class="fineText">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">pointish</div>
    <div class="pointish">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">hpointish</div>
    <div class="hpointish">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">details</div>
    <div class="details">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">upper</div>
    <div class="upper">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>
    <br/>
    <div class="gClass">cleanText</div>
    <div class="cleanText">That being said, welcome to GallantOne.com, home of software engineer and web producer Greg A. Gallant. Brining ideas to a technological life is the everyday challenge that keeps the digital world moving and what essentially keeps myself up to par as a professional company builder.</div>

</div>


