
<style type="text/css">

    .typeSheet {
        height:100%; font-family:arial,sans-serif; background-color:#ffffff; color:#000000; padding:5px; border:1px solid #333333;
    }

    .gClass {
        float:left;
        margin:5px;
        font-size:11pt;
    }

    h1 {
        font-weight:800%; font-size:14pt;  font-family:Trebuchet MS, Arial, sans-serif;
    }

</style>



<div class="typeSheet">
<strong>GallantOne.com Typography</strong>
    <hr/>
    <div class="gClass">h1</div>
    <h1>This is a header</h1>
</div>

