<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GallantOne.com ')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/one.css')
                        ->prependStylesheet($this->basePath() . '/css/one-media-queries.css')
                        ->prependStylesheet($this->basePath() . '/css/one_portfolio.css')
                        ->prependStylesheet($this->basePath() . '/js/fancybox/source/jquery.fancybox.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/goport.js')
                                      ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
                                      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ?>

    </head>
    <body>
    <img alt="full screen background image" src="/images/one/gg_sunset.png" id="full-screen-background-image" />
    <div id="pagewrap">
        <header id="header">
            <div class="goHeader">
                <a href="/"><img id="goLogo" alt="GallantOne.com" border="0" src="/images/one/one_logo.png" /></a>
            </div>
            <?php echo $this->partial("application/index/menu.phtml", "array()"); ?>
            <div class="goLine"></div>
            <div class="authMenu">
                <div class="loginPlacement"><a class="loginPlacement" href="/login">login</a> / <a class="loginPlacement" href="/register">register</a></div>
            </div>
        </header>
            <?php echo $this->content; ?>
        <!-- end content -->
    </div>
    </body>

</html>
