<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GallantOne.com ')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/gallantone.css')
                        ->prependStylesheet($this->basePath() . '/js/fancybox/source/jquery.fancybox.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/goport.js')
                                      ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
                                      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ?>

    </head>
    <body>
    <div class="motherboard">
        <div class="leftFade"><img src="/images/leftFadeEdge.jpg"/></div>
        <div class="centerContent">
            <div class="headerLogo"><a href="<?php echo $this->url('home')?>"><img border="0" src="/images/logoHeader.jpg"/></a></div>
            <?php echo $this->partial("application/index/menu.phtml", "array()"); ?>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->partial("application/index/rightContent.phtml", "array()"); ?>

    <div class="rightFade"><img src="/images/rightFadeEdge.jpg"/></div>
    </div>
    </body>
</html>
