<html>
    <head>

    <?php echo
    $this->headLink()->prependStylesheet('/css/gallantlight.css')
    ?>

    <?php echo $this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
        ?>
    <script language="javascript" type="text/javascript">
        $(document).ready(function() {
            $('#closeButton').click(function() {
                parent.$.fancybox.close();

            });
        });
    </script>
    </head>
    <body>

    <div class="portContentBox">
        <?php echo $this->content; ?>
        <div class="closeButtonPos"><a class="button orange" id="closeButton" href="#">Close</a></div>
    </div>
    </body>

</html>