<html>
    <head>

    <?php echo
    $this->headLink()->prependStylesheet('/css/gallantlight.css')
    ?>

    <?php echo $this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
        ?>
    <script language="javascript" type="text/javascript">
        $(document).ready(function() {
            $('.closeButton').click(function() {
                parent.$.fancybox.close();

            });
        });
    </script>
    </head>
    <body>

    <div style="padding:30px 50px 30px 40px; width:700px; fixed-width:700px; color:#333333;">

        <b> THE PORT LAYOUT</b>
        <?php echo $this->content; ?>

        <a class="closeButton" id="closeButton" href="#">Close</a>
    </div>
    </body>

</html>