<div class="mainPlateHead">
    <h2>Unused base page</h2>

    <div>

        <table class="table">
            <tr>
                <th>Client</th>
                <th>type_id</th>
                <th>Image</th>
            </tr>
            <?php foreach ($clients as $client) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($client->getName());?></td>
                    <td><?php echo $this->escapeHtml($client->getClientTypeId());?></td>
                    <td><?php echo $this->escapeHtml($client->getImage());?></td>
                </tr>
            <?php endforeach; ?>

        </table>


    </div>

</div>