<div style="width:250px; top:25px; display:inline-block">
<div style="margin-left:5px; margin-top:0px;">
    <div style="font-weight:bold; font-size:12pt;"><?php echo $client->getName(); ?></div>
    <div style="font-size:11pt;"><?php echo $client->getDetails(); ?></div>
    <div style="margin-top:10px;font-size:11pt; text-align:right"><a name="learnMore" class="button orange" id="learnMore<?php echo $client->getId(); ?>" href="#">Learn More</a></div>
</div>
</div>