<div style="width:250px; top:25px; display:inline-block">
<div style="margin-left:5px; margin-top:0px;">
    <div style="font-weight:bold; font-size:12pt;"><?php echo $client->name?></div>
    <div style="font-size:11pt;"><?php echo $client->details?></div>
    <div style="font-size:11pt; text-align:right"><a name="learnMore" class="learnMore" id="learnMore<?php echo $client->id ?>" href="#">Learn More</a></div>
</div>
</div>