<div>
    <div class="lightScreenContent">
                    <div style="font-weight:bold; font-size:12pt;"><?php echo $this->escapeHtml($client->getName());?></div>
                    <div style="font-style:italic; font-size:8pt;"><a target="toClient" href="<?php echo $this->escapeHtml($client->getUrl());?>"><?php echo $this->escapeHtml($client->getUrl()) ?></a></div>
                    <hr>
                    <div style="font-size:9pt;">
                        <strong>Technology:</strong>
                        <?php echo $this->escapeHtml($client->getTech());?></div>
                    <hr>
                    <div><?php //echo $this->escapeHtml($client->details);?></div>
                    <div style="font-size:9pt;"><?php echo $client->getThejob();?></div>
    </div>
    <div class="lightScreenImage">
        <img width="300px" height="220px" src="/images/clients/<?php echo $this->escapeHtml($client->getImage());?>"/>
    </div>

</div>