<div style="height:100%;">
    <div class="preLoader" id="preLoader">
        <img src="/images/loader.gif"/>
    </div>
    <div class="portfolioContent" id="portfolioContent" style="display:none">
        <div>
            <h1>Portfolio</h1>
            <div>

                <div>

                    <div class="mobileMenu"><a href="/mobile/1" class="mButton black">Web Software</a></div>
                    <div class="mobileMenu"><a href="/mobile/2" class="mButton black">Web Design</a></div>
                    <br/>
                    <div class="mobileMenu"><a href="/mobile/3" class="mButton black">Print Design</a></div>
                    <div class="webMenuLast"><a href="/mobile/4" class="mButton black">Logo Design</a></div>
                </div>
                <?php $ccount = 0; ?>
                <?php foreach ($clients as $client) : ?>
                <!-- The Screen -->
                <div class="mobileScreenContent" id="mobileScreenContent<?php echo $ccount; ?>">

                    <!-- table width="730px; height:370px;"-->
                    <div style="display:block; font-weight:bold;" id="innerPortLeft<?php echo $ccount; ?>">
                   <?php echo $client->getName(); ?>
                    </div>
                    <div style="display:block;" id="innerPortRight<?php echo $ccount;?>">
                            <?php if ($client->getId() == 18) { $this->iWidth = '400px'; $this->iHeight='294px'; } ?>
                            <img id="portfolioImage<?php echo $ccount ?>" alt="portfolioImage" width="250px" height="125px" style="border:1px outset #333333;" src="/images/clients/<?php echo $this->escapeHtml($client->getImage());?>"/>
                    </div>
                </div>
                <?php $ccount++; ?>
                <?php endforeach; ?>
            </div>
        </div>


    </div>
</div>
<input type="hidden" id="totalScreenContent" value="<?php echo $this->totalContent ?>">