<!-- portcontrol.phtml Image Controls -->
<?php $ccount = 0 ?>
<?php foreach ($clients as $client) : ?>
    <div class="portControlLineup">
        <a name="imageControl" id="imageControl<?php echo $ccount ?>" class="imageControl" href="#">
            <?php if ($client->getId() == 18) { $this->tWidth = '80px'; $this->iHeight='50px'; } ?>
            <img border="0" width="<?php echo $this->tWidth ?>" height="<?php echo $this->tHeight ?>" src="/images/clients/<?php echo $client->getImage();?>"/></a>
    </div>
<?php $ccount++ ?>
<?php endforeach ?>
