<div style="background-color:#060f0d;">
    <div class="preLoader" id="preLoader">
        <img src="/images/loader.gif"/>
    </div>
    <div class="portfolioContent" id="portfolioContent" style="display:none">
        <div class="fatherBoard">
            <div class="portScreen">

                <div style="padding:10px 10px 10px 12px">

                 <div class="webMenu"><a href="/portfolio/web/1" class="button black">Web Software</a></div>
                 <div class="webMenu"><a href="/portfolio/web/2" class="button black">Web Design</a></div>
                 <div class="webMenu"><a href="/portfolio/web/3" class="button black">Print Design</a></div>
                 <div class="webMenuLast"><a href="/portfolio/web/4" class="button black">Logo Design</a></div>
                </div>
             <?php $ccount = 0; ?>
            <?php foreach ($clients as $client) : ?>

                <!-- The Screen -->
                <div class="portScreenContent" id="portScreenContent<?php echo $ccount ?>">

                    <table width="730px;">
                    <tr>
                    <td>
                    <div style="width:250px; top:25px; display:inline-block">
                        <div style="margin-left:5px; margin-top:0px;">
                            <div style="font-weight:bold; font-size:12pt;"><?php echo $client->name?></div>
                            <div style="font-size:11pt;"><?php echo $client->details?></div>
                            <div style="font-size:11pt; text-align:right"><a class="learnMore" id="learnMore" href="#">Learn More</a></div>
                        </div>
                    </div>
                    </td><td>
                    <div style="padding-top:30px; width:400px; height:294px;  display:inline-block">
                        <img style="border:1px outset #333333;" src="http://www.gallantone.com/gfx/clients/<?php echo $this->escapeHtml($client->image);?>"/>
                    </div>
                    </td>
                    </tr>
                    </table>
                </div>
                    <div style="padding-top:40px; padding-left:80px; display:inline-block;">
                        <img width="80" height="50" src="http://www.gallantone.com/gfx/clients/<?php echo $this->escapeHtml($client->image);?>"/>
                    </div>
            <?php $ccount++; ?>
            <?php endforeach; ?>

            </div>
        </div>


    </div>
</div>
<input type="hidden" id="totalScreenContent" value="<?php echo $this->totalContent ?>">