<!DOCTYPE html>
<html>
    <head>

    <?php echo
    $this->headLink()->prependStylesheet('/css/gallantmedia.css')
    ?>

    <link href="/css/media-queries.css" rel="stylesheet" type="text/css">

    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
        ?>

        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
        <![endif]-->
    </head>
    <body>
        <div id="pagewrap">

            <header id="header"><img src="/images/gallantmedia/logo.gif"/></header>
            <?php echo $this->content; ?>
        </div>
    </body>

</html>