<div class="formWrap">
    <h1>Login</h1>
   <?php

$login_form = $this->login_form;

$login_form->setAttribute('action', $this->url(
    'login',
    array(
        'action' => 'login',
        'email' => $this->email,
        'password' => $this->password,
    )
));

$login_form->prepare();

if ($error != null)  {
    echo $error;
}

echo $this->form()->openTag($login_form);
echo $this->formRow($login_form->get('email'));
echo "<br/>";
echo $this->formRow($login_form->get('password'));
echo "<br/>";
echo $this->formSubmit($login_form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
