<?php

$form = $this->form;

$form->setAttribute('action', $this->url(
    'login',
    array(
        'action' => 'login',
        'email' => $this->email,
        'password' => $this->password,
    )
));

$form->prepare();

if ($error != null)  {
    echo $error;
}

var_dump($this->form->getMessages());

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

