<h1>Login</h1>
<div class="formWrap">
   <?php

$form = $this->form;

$form->setAttribute('action', $this->url(
    'login',
    array(
        'action' => 'login',
        'email' => $this->email,
        'password' => $this->password,
    )
));

$form->prepare();

if ($error != null)  {
    echo $error;
}

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo "<br/>";
echo $this->formRow($form->get('password'));
echo "<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
