<h1>Register</h1>
<?php

$form = $this->form;

$form->setAttribute('action', $this->url(

    'register',
    array(
        'action' => 'register',
        'email' => $this->email,
        'password' => $this->password,
        'confirm_password' => $this->confirm_password,
        'first_name' => $this->first_name,
        'last_name' => $this->last_name,
    )
));

$form->prepare();

if ($exception != null) {
   echo "<p>".$exception."<p>";
}

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo "<br/>";
echo $this->formRow($form->get('password'));
echo "<br/>";
echo $this->formRow($form->get('confirm_password'));
echo "<br/>";
echo $this->formRow($form->get('first_name'));
echo "<br/>";
echo $this->formRow($form->get('last_name'));
echo "<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

