<html>
<head>

    <?php echo
$this->headLink()->prependStylesheet('/css/gallantnyc.css')
    ?>

    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js')
    ?>

</head>
<body>

<div id="bg">
    <div>
        <table cellspacing="0" cellpadding="0">
            <tr>
                <td><img src="/images/gnyc/newback.jpg" alt="" /></td>
            </tr>
        </table>
    </div>
</div>
<div id="cont">
    <div class="transbox">
        <!-- content -->
        <?php echo $this->content; ?>
    </div>
</div>
</body>

</html>