<div class="details" style="padding:5px 10px 5px 5px; background-color:#dfdfdf;">
<a href="/admin/">Home</a> |
<a target="mantis" href="http://mantis.gallantnyc.com">Mantis</a> |
<a href="/admin/phpinfo">PHPInfo</a> |
<a href="/admin/typography">Typography</a> |
<a href="/clients">Clients</a> |
<a href="/admin/resources">Resources</a> |
<a href="/codestudio">Code Studio</a> |
<a href="/networks">Networks</a>
</div>