
<?php echo $this->partial("application/index/photoHead.phtml", array());  ?>
<div class="mainPlateHead">
    <div class="mainPlate">
        <div style="z-index:5;  width:733px;">

            <?php echo $this->partial("application/index/leftFrontPanel.phtml", array());  ?>
            <div class="infoPanel">

                <div class="resumePanel">
                    <a href="/assets/GregGallantResume.docx">Download Resum&#233;</a>
                    <br/>
                    <em>Word .docx Format</em>
                </div>
                <div class="resumePanel">
                    Contact Greg Gallant:
                    <br/>
                    &nbsp;<em><a href="mailto:greggallant2005@gmail.com">greggallant2005@gmail.com</a></em>
                    <br/>-or-<br/>
                    &nbsp;<em><a href="mailto:greg@gallantone.com">greg@gallantone.com</a></em>
                </div>
            </div>

        </div>
    </div>
</div>





