<div class="menuBar">
    <div style="text-align:right; font-family:Arial,sans-serif; font-size:10pt; padding-left:7px;  padding-top:5px;">
        <div class="menuPlacement"><a class="menuPlacement" href="/portfolio/1">portfolio</a></div>
        <div class="linePlacement">|</div>
        <div class="menuPlacement"><a class="menuPlacement" href="/assets/GregGallantResume.docx">resum&#233;</a></div>
        <div class="linePlacement">|</div>
        <div class="menuPlacementLast"><a class="menuPlacement" href="http://www.linkedin.com/in/greggallant" target="_linkedin">Linked-in</a></div>
    </div>
</div>