<div class="rightArticleBar">
    <img style="z-index:3" src="/images/rightArticleBar.jpg"/>
    <div style="position:absolute; z-index:5; left:10px; top:38px; color:#ffffff;">
        <div class="panelText1">
            <div style="position:relative; padding-bottom:8px; left:-25px;"><img border="0" src="/images/textline_up.jpg"/></div>
            <strong>Greg A. Gallant</strong> is a professional
            technologist and software engineer and web designer
            with over 14 years of experience working in New York City.
            <br/>
            <br/>
            Specializations and experience include the building of several small technology companies using a multitude of programming languages including <a target="springsource" href="http://springsource.org">Java Spring MVC 3</a>, <a target="php" href="http://www.php.net">PHP</a> <a href="http://framework.zend.com">Zend 2 Framework</a> and <a href="http://ellislab.com/codeigniter">CodeIgniter</a>, <a href="http://www.python.org">Python</a>, Javascript, and <a href="http://jquery.com">JQuery</a>. This includes database programming using <a href="http://www.mysql.com">MySQL</a>, <a href="http://www.oracle.com">Oracle</a>, and <a href="http://www.postgresql.org">PostGreSQL</a>.
            <div style="position:relative; padding-top:8px; left:-25px;"><img border="0" src="/images/textline_down.jpg"/></div>
            <br/>
        </div>
        <div style="position:relative; top:500px;">
            <!--
                    <a href="<?php //echo $this->url('album') ?>">The Album Module</a>
                    <br/>
                    <a href="<?php //echo $this->url('portfolio') ?>">The Portfolio Module</a>
                    <br/>
                    <a href="<?php //echo $this->url('portfolio/') ?>/web/1">The JQuery Suite Module</a>
                        <br/>
                    <a href="http://blog.evan.pro" target="evanpro">Evan.pro</a>
                    <br/>
                    http://speckyboy.com/2010/11/08/40-essential-css-templates-resources-and-downloads/
-->
        </div>
    </div>
</div>